### ISSUE TITLE
Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by yashrajb** [rsmbl/Resemble.js#192]
This error is frustrated me. here is the error
it is running fine on locally but failed in Jenkins 
```
Error: Cannot find module '../build/Release/canvas.node'
    at Object.<anonymous> (/workspace/node_modules/resemblejs/node_modules/canvas/lib/bindings.js:3:18)
    at Object.require.extensions.(anonymous function) [as .js] (/workspace/node_modules/testcafe/src/compiler/test-file/api-based.js:84:21)
    at Object.<anonymous> (/workspace/node_modules/resemblejs/node_modules/canvas/lib/canvas.js:9:18)
    at Object.require.extensions.(anonymous function) [as .js] (/workspace/node_modules/testcafe/src/compiler/test-file/api-based.js:84:21)
    at Object.<anonymous> (/workspace/node_modules/resemblejs/node_modules/canvas/index.js:1:16)
    at Object.require.extensions.(anonymous function) [as .js] (/workspace/node_modules/testcafe/src/compiler/test-file/api-based.js:84:21)
    at /workspace/node_modules/resemblejs/resemble.js:27:18
    at /workspace/node_modules/resemblejs/resemble.js:15:26
    at Object.<anonymous> (/workspace/node_modules/resemblejs/resemble.js:19:3)
    at Object.require.extensions.(anonymous function) [as .js] (/workspace/node_modules/testcafe/src/compiler/test-file/api-based.js:84:21)
```
i am also getting errors related to "npm-gyp"

**Comment by jamescryer** [comment]
I saw the same issue when upgrading to node 13.  After removing node_modules and running `npm install` it was working fine for me.

**Comment by Abhinandan-Kushwaha** [comment]
Facing the same issue on the latest version

**Comment by milahu** [comment]
upstream issue: https://github.com/Automattic/node-canvas/issues/2135#issuecomment-1400307682

force rebuild of canvas:

```
( cd node_modules/canvas && npx node-pre-gyp install --fallback-to-build --update-binary )
```
